.TH "Cli" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cli
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cli\&.h>\fP
.PP
Inherited by \fBMockRng\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::vector< std::string > \fBprocess\fP ()"
.br
.RI "All methods implements Class \fBCli\fP defined in \fBCli\&.h\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Module handling everythin related to our Command line interface\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::string > Cli::process ()\fC [virtual]\fP"

.PP
All methods implements Class \fBCli\fP defined in \fBCli\&.h\fP\&. Public method processing input from stdin\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
