.TH "Client" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.RI "A method that waits CLI input from method getCliInput\&. The method will break if input is interpreted as exit or continue by sending the request to be handled\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DbType \fBtype\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Client::setup ()"

.PP
A method that waits CLI input from method getCliInput\&. The method will break if input is interpreted as exit or continue by sending the request to be handled\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
