.TH "Connection" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Connection
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBgetConnectionStatus\fP ()"
.br
.ti -1c
.RI "bool \fBsendServerRequest\fP (std::string &request, std::string &result)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSshConnector\fP * \fBm_conn\fP"
.br
.ti -1c
.RI "\fBConnectionStream\fP * \fBstream\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
