.TH "DatabaseItem" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseItem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabaseItem\fP (std::vector< std::string > _actors, std::string _title, std::string _genre, std::string _director)"
.br
.ti -1c
.RI "void \fBsetFeature\fP (\fBTags\fP feature)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetActors\fP ()"
.br
.ti -1c
.RI "std::string \fBgetTitle\fP () const"
.br
.ti -1c
.RI "std::string \fBgetDirector\fP ()"
.br
.ti -1c
.RI "std::string \fBgetGenre\fP ()"
.br
.ti -1c
.RI "std::string \fBgetDir\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdirectory\fP"
.br
.ti -1c
.RI "std::string \fBm_title\fP"
.br
.ti -1c
.RI "std::string \fBm_genre\fP"
.br
.ti -1c
.RI "std::string \fBm_director\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBm_actors\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
