.TH "JsonParser" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonParser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparser\fP ()"
.br
.ti -1c
.RI "void \fBupdateDB\fP ()"
.br
.ti -1c
.RI "std::map< std::string, std::vector< std::string > > \fBgetParsed\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fB_parsed\fP"
.br
.ti -1c
.RI "std::map< std::string, std::vector< std::string > > \fB_map\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
