.TH "Json::Value::ValueHolder" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::Value::ValueHolder
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LargestInt \fBint_\fP"
.br
.ti -1c
.RI "LargestUInt \fBuint_\fP"
.br
.ti -1c
.RI "double \fBreal_\fP"
.br
.ti -1c
.RI "bool \fBbool_\fP"
.br
.ti -1c
.RI "char * \fBstring_\fP"
.br
.ti -1c
.RI "ObjectValues * \fBmap_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
