.TH "Json::BuiltStyledStreamWriter" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::BuiltStyledStreamWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJson::StreamWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuiltStyledStreamWriter\fP (JSONCPP_STRING const &indentation, \fBCommentStyle::Enum\fP cs, JSONCPP_STRING const &colonSymbol, JSONCPP_STRING const &nullSymbol, JSONCPP_STRING const &endingLineFeedSymbol, bool useSpecialFloats, unsigned int precision, \fBPrecisionType\fP precisionType)"
.br
.ti -1c
.RI "int \fBwrite\fP (\fBValue\fP const &root, JSONCPP_OSTREAM *sout) JSONCPP_OVERRIDE"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef std::vector< JSONCPP_STRING > \fBChildValues\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBwriteValue\fP (\fBValue\fP const &value)"
.br
.ti -1c
.RI "void \fBwriteArrayValue\fP (\fBValue\fP const &value)"
.br
.ti -1c
.RI "bool \fBisMultilineArray\fP (\fBValue\fP const &value)"
.br
.ti -1c
.RI "void \fBpushValue\fP (JSONCPP_STRING const &value)"
.br
.ti -1c
.RI "void \fBwriteIndent\fP ()"
.br
.ti -1c
.RI "void \fBwriteWithIndent\fP (JSONCPP_STRING const &value)"
.br
.ti -1c
.RI "void \fBindent\fP ()"
.br
.ti -1c
.RI "void \fBunindent\fP ()"
.br
.ti -1c
.RI "void \fBwriteCommentBeforeValue\fP (\fBValue\fP const &root)"
.br
.ti -1c
.RI "void \fBwriteCommentAfterValueOnSameLine\fP (\fBValue\fP const &root)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBhasCommentForValue\fP (const \fBValue\fP &value)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ChildValues \fBchildValues_\fP"
.br
.ti -1c
.RI "JSONCPP_STRING \fBindentString_\fP"
.br
.ti -1c
.RI "unsigned int \fBrightMargin_\fP"
.br
.ti -1c
.RI "JSONCPP_STRING \fBindentation_\fP"
.br
.ti -1c
.RI "\fBCommentStyle::Enum\fP \fBcs_\fP"
.br
.ti -1c
.RI "JSONCPP_STRING \fBcolonSymbol_\fP"
.br
.ti -1c
.RI "JSONCPP_STRING \fBnullSymbol_\fP"
.br
.ti -1c
.RI "JSONCPP_STRING \fBendingLineFeedSymbol_\fP"
.br
.ti -1c
.RI "bool \fBaddChildValues_\fP: 1"
.br
.ti -1c
.RI "bool \fBindented_\fP: 1"
.br
.ti -1c
.RI "bool \fBuseSpecialFloats_\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBprecision_\fP"
.br
.ti -1c
.RI "\fBPrecisionType\fP \fBprecisionType_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "int Json::BuiltStyledStreamWriter::write (\fBValue\fP const & root, JSONCPP_OSTREAM * sout)\fC [virtual]\fP"
Write \fBValue\fP into document as configured in sub-class\&. Do not take ownership of sout, but maintain a reference during function\&. 
.PP
\fBPrecondition:\fP
.RS 4
sout != NULL 
.RE
.PP
\fBReturns:\fP
.RS 4
zero on success (For now, we always return zero, so check the stream instead\&.) 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIstd::exception\fP possibly, depending on configuration 
.RE
.PP

.PP
Implements \fBJson::StreamWriter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
