.TH "Json::Reader::ErrorInfo" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::Reader::ErrorInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBToken\fP \fBtoken_\fP"
.br
.ti -1c
.RI "JSONCPP_STRING \fBmessage_\fP"
.br
.ti -1c
.RI "Location \fBextra_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
