.TH "Logger::map_init_helper< T >" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger::map_init_helper< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmap_init_helper\fP (T &d)"
.br
.ti -1c
.RI "\fBmap_init_helper\fP & \fBoperator()\fP (typename T::key_type const &key, typename T::mapped_type const &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T & \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
