.TH "MockObserver" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MockObserver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMediaHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMOCK_METHOD1\fP (\fBupdate\fP, int(\fBRequest\fP &))"
.br
.ti -1c
.RI "int \fBupdate\fP (\fBRequest\fP &request) override"
.br
.RI "receives new request from client "
.ti -1c
.RI "void \fBstartThreads\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBClient\fP * \fBp_client\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int MediaHandler::update (\fBRequest\fP & request)\fC [override]\fP, \fC [virtual]\fP, \fC [inherited]\fP"

.PP
receives new request from client \fBMediaHandler::update\fP method update 
.PP
\fBParameters:\fP
.RS 4
\fIrequest\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBObserver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
