.TH "MovieDatabase" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MovieDatabase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDatabase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBpushItem\fP (const \fBDatabaseItem\fP &m_item) override"
.br
.ti -1c
.RI "\fBDatabaseItem\fP \fBfetchItem\fP (const std::string &title) override"
.br
.ti -1c
.RI "long \fBgetNumberOfItem\fP () override"
.br
.ti -1c
.RI "void \fBpurgeItem\fP (const \fBDatabaseItem\fP &m_item) override"
.br
.ti -1c
.RI "void \fBprintAll\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
