.TH "NotImplementedException" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NotImplementedException \-  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Database\&.h>\fP
.PP
Inherits std::logic_error\&.
.SH "Detailed Description"
.PP 


A module that works as an interface for subclasses and let them perform database actions 

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
