.TH "Observer" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Observer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMediaHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBupdate\fP (\fBRequest\fP &)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual int Observer::update (\fBRequest\fP &)\fC [pure virtual]\fP"
Update the state of this observer 
.PP
\fBParameters:\fP
.RS 4
\fI\fBRequest\fP\fP of update 
.RE
.PP

.PP
Implemented in \fBMediaHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
