.TH "ObserverTest" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObserverTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, std::vector< std::string > > \fBm_loadedMovieMap\fP"
.br
.ti -1c
.RI "std::map< std::string, std::vector< std::string > > \fBm_loadedSeriesMap\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
