.TH "QueueRequestOp" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueRequestOp \- push incoming request to queue  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
push incoming request to queue 

pop requests from queue
.PP
pushRequest 
.PP
\fBParameters:\fP
.RS 4
\fIm_request\fP incoming request about to be queued
.RE
.PP
popRequest 
.PP
\fBReturns:\fP
.RS 4
popped request ready to process 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
