.TH "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Tuple1 , class Tuple2 > static bool \fBEq\fP (const Tuple1 &t1, const Tuple2 &t2)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
