.TH "std::tr1::tuple<>" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::tuple<>
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtuple\fP (const \fBtuple\fP &)"
.br
.ti -1c
.RI "\fBtuple\fP & \fBoperator=\fP (const \fBtuple\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
