.TH "Tags" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tags \- A module representing the content of a database item\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DatabaseItem\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBs_title\fP"
.br
.ti -1c
.RI "std::string \fBs_genre\fP"
.br
.ti -1c
.RI "std::string \fBs_director\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBs_actors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A module representing the content of a database item\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
