.TH "testing::internal::XmlUnitTestResultPrinter" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::XmlUnitTestResultPrinter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::EmptyTestEventListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlUnitTestResultPrinter\fP (const char *output_file)"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationEnd\fP (const \fBUnitTest\fP &unit_test, int iteration)"
.br
.ti -1c
.RI "void \fBListTestsMatchingFilter\fP (const std::vector< \fBTestCase\fP *> &test_cases)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrintXmlTestsList\fP (std::ostream *stream, const std::vector< \fBTestCase\fP *> &test_cases)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
