.TH "testing::internal::ValueArray4< T1, T2, T3, T4 >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ValueArray4< T1, T2, T3, T4 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueArray4\fP (T1 v1, T2 v2, T3 v3, T4 v4)"
.br
.ti -1c
.RI "template<typename T > \fBoperator ParamGenerator< T >\fP () const"
.br
.ti -1c
.RI "\fBValueArray4\fP (const \fBValueArray4\fP &other)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
