.TH "testing::WithParamInterface< T >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::WithParamInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::TestWithParam< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const ParamType & \fBGetParam\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class TestClass > class \fBinternal::ParameterizedTestFactory\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
