.TH "testing::EmptyTestEventListener" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::EmptyTestEventListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::TestEventListener\fP\&.
.PP
Inherited by \fBtesting::internal::JsonUnitTestResultPrinter\fP, and \fBtesting::internal::XmlUnitTestResultPrinter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnTestProgramStart\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationStart\fP (const \fBUnitTest\fP &, int)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpStart\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpEnd\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseStart\fP (const \fBTestCase\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestStart\fP (const \fBTestInfo\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestPartResult\fP (const TestPartResult &)"
.br
.ti -1c
.RI "virtual void \fBOnTestEnd\fP (const \fBTestInfo\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseEnd\fP (const \fBTestCase\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownStart\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownEnd\fP (const \fBUnitTest\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationEnd\fP (const \fBUnitTest\fP &, int)"
.br
.ti -1c
.RI "virtual void \fBOnTestProgramEnd\fP (const \fBUnitTest\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
