.TH "testing::internal::IsAProtocolMessage< T >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsAProtocolMessage< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::internal::bool_constant< ImplicitlyConvertible< const T *, const ::ProtocolMessage *>::value||ImplicitlyConvertible< const T *, const ::proto2::Message *>::value >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
