.TH "testing::internal::TestCaseNameIs" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestCaseNameIs
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCaseNameIs\fP (const std::string &name)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBTestCase\fP *test_case) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
