.TH "testing::internal::IsRecursiveContainerImpl< C, true, true >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsRecursiveContainerImpl< C, true, true >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBIteratorTraits\fP< typename C::iterator >::value_type \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBis_same\fP< value_type, C > \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
