.TH "testing::internal::TestFactoryBase" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestFactoryBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::internal::ParameterizedTestFactory< TestClass >\fP, and \fBtesting::internal::TestFactoryImpl< TestClass >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBTest\fP * \fBCreateTest\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
