.TH "testing::internal::TestFactoryImpl< TestClass >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestFactoryImpl< TestClass >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::internal::TestFactoryBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBTest\fP * \fBCreateTest\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
