.TH "testing::ScopedTrace" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::ScopedTrace
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBScopedTrace\fP (const char *file, int line, const T &message)"
.br
.ti -1c
.RI "\fBScopedTrace\fP (const char *file, int line, const char *message)"
.br
.ti -1c
.RI "\fBScopedTrace\fP (const char *file, int line, const std::string &message)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
