.TH "testing::internal::linked_ptr< T >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::linked_ptr< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBelement_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlinked_ptr\fP (T *ptr=NULL)"
.br
.ti -1c
.RI "template<typename U > \fBlinked_ptr\fP (\fBlinked_ptr\fP< U > const &ptr)"
.br
.ti -1c
.RI "\fBlinked_ptr\fP (\fBlinked_ptr\fP const &ptr)"
.br
.ti -1c
.RI "template<typename U > \fBlinked_ptr\fP & \fBoperator=\fP (\fBlinked_ptr\fP< U > const &ptr)"
.br
.ti -1c
.RI "\fBlinked_ptr\fP & \fBoperator=\fP (\fBlinked_ptr\fP const &ptr)"
.br
.ti -1c
.RI "void \fBreset\fP (T *ptr=NULL)"
.br
.ti -1c
.RI "T * \fBget\fP () const"
.br
.ti -1c
.RI "T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "T & \fBoperator*\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (T *p) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (T *p) const"
.br
.ti -1c
.RI "template<typename U > bool \fBoperator==\fP (\fBlinked_ptr\fP< U > const &ptr) const"
.br
.ti -1c
.RI "template<typename U > bool \fBoperator!=\fP (\fBlinked_ptr\fP< U > const &ptr) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename U > class \fBlinked_ptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
