.TH "testing::internal::IsRecursiveContainerImpl< C, true, false >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsRecursiveContainerImpl< C, true, false >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::internal::bool_constant< bool_value >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
