.TH "testing::internal::AssertHelper" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::AssertHelper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertHelper\fP (TestPartResult::Type type, const char *file, int line, const char *message)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBMessage\fP &message) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
