.TH "testing::internal::ParameterizedTestCaseInfoBase" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestCaseInfoBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::internal::ParameterizedTestCaseInfo< TestCase >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const std::string & \fBGetTestCaseName\fP () const =0"
.br
.ti -1c
.RI "virtual TypeId \fBGetTestCaseTypeId\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBRegisterTests\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
