.TH "testing::internal::linked_ptr_internal" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::linked_ptr_internal
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBjoin_new\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP (\fBlinked_ptr_internal\fP const *ptr) GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)"
.br
.ti -1c
.RI "bool \fBdepart\fP () GTEST_LOCK_EXCLUDED_(g_linked_ptr_mutex)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
