.TH "testing::internal::TestMetaFactoryBase< ParamType >" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestMetaFactoryBase< ParamType >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBTestFactoryBase\fP * \fBCreateTestFactory\fP (ParamType parameter)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
