.TH "testing::internal::ParameterizedTestCaseRegistry" 3 "Mon Oct 15 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestCaseRegistry
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class TestCase > \fBParameterizedTestCaseInfo\fP< \fBTestCase\fP > * \fBGetTestCasePatternHolder\fP (const char *test_case_name, \fBCodeLocation\fP code_location)"
.br
.ti -1c
.RI "void \fBRegisterTests\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
