.TH "CliTest" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CliTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCli\fP * \fBcli\fP"
.br
.ti -1c
.RI "std::string \fBFILE_DIR\fP = '~/repo/media_fw/mediaFW/data/'"
.br
.ti -1c
.RI "std::string \fBTEST_FILE\fP = FILE_DIR + 'testfile\&.txt'"
.br
.ti -1c
.RI "Category \fBcat2\fP = Category::Series"
.br
.ti -1c
.RI "Category \fBcat\fP = Category::Movie"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
