.TH "CommandLineParser" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandLineParser
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCli\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBRequest\fP \fBprocess\fP ()=0"
.br
.ti -1c
.RI "virtual \fBRequest\fP \fBprocess\fP (std::string &)=0"
.br
.ti -1c
.RI "virtual \fBRequest\fP \fBinterprete\fP (std::vector< std::string > &)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
