.TH "JsonTest" 3 "Tue Nov 13 2018" "mediaFW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, std::vector< std::string > > \fBm_loadedMovieMap\fP"
.br
.ti -1c
.RI "std::map< std::string, std::vector< std::string > > \fBm_loadedSeriesMap\fP"
.br
.ti -1c
.RI "const std::string \fBTITLE\fP = 'title'"
.br
.ti -1c
.RI "const std::string \fBGENRE\fP = 'genre'"
.br
.ti -1c
.RI "const std::string \fBACTOR\fP = 'actor'"
.br
.ti -1c
.RI "const std::string \fBDIRECTOR\fP = 'director'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mediaFW from the source code\&.
